baseURL = 'https://conragan.com'
languageCode = 'en-us'
title = 'Kai Conragan'

theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"
publishDir = "docs"

[markup.highlight]
style = "github-dark"

[params]
  author = "Kai Conragan"
  info = "Tech leader, UX Designer, and Photographer."
  description = "Kai Conragan's personal website"
  keywords = "ux, ui, design, technology, google, photography"
  avatarurl = "img/headshot.png"
  #gravatar = "kai@conragan.com"

  faviconSVG = "img/favicon.svg"
  favicon_32 = "img/favicon-32x32.png"
  favicon_16 = "img/favicon-16x16.png"
  
  colorScheme = "auto"
  hidecolorschemetoggle = false
  
  # Social links
[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/kconragan/"
[[params.social]]
  name = "LinkedIn"
  icon = "fa fa-linkedin fa-2x"
  weight = 2
  url = "https://www.linkedin.com/in/kconragan/"
[[params.social]]
  name = "Twitter"
  icon = "fa fa-twitter fa-2x"
  weight = 3
  url = "https://twitter.com/kconragan/"

# Menu links
#[[menu.main]]
#  name = "Projects"
#  weight = 1
#  url  = "projects/"