baseURL = 'https://conragan.com'
languageCode = 'en-us'
title = 'Kai Conragan'

theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"
publishDir = "docs" # to support github pages

[markup.highlight]
style = "github-dark"

enableGitInfo = true

# Menu links
[[menu.main]]
   name = "Photography"
   weight = 1
   url  = "photography/"
#[[menu.main]]
#   name = "Blog"
#   weight = 2
#   url = "blog/"

[params]

  # info
  author = "Kai Conragan"
  info = "Tech leader, UX Designer, Writer, and [Photographer](/photography/)."
  description = "Kai Conragan's personal website"
  keywords = "landscape photography, sports photography, wildlife photogrpahy, bird photography, design, travel, ux, user experience"

  # images
  avatarurl = "img/headshot.png"
  faviconSVG = "img/favicon.svg"
  favicon_32 = "img/favicon-32x32.png"
  favicon_16 = "img/favicon-16x16.png"
  
  # style
  colorScheme = "auto"
  hidecolorschemetoggle = false
  customCSS = ["css/bulma.min.css", "css/lightgallery.min.css", "css/conragan.css"]
  
  # Google Analytics
  [params.googleTagManager]
    id = "G-4R2W76V53L"

  # Pinterest
  [params.meta]
    name = "p:domain_verify"
    content = "5e42b91db4d05707d32a9894e67423c5"

  # Social links
  [[params.social]]
    name = "Github"
    icon = "fa fa-github fa-2x"
    weight = 1
    url = "https://github.com/kconragan/"
  [[params.social]]
    name = "LinkedIn"
    icon = "fa fa-linkedin fa-2x"
    weight = 2
    url = "https://www.linkedin.com/in/kconragan/"
  [[params.social]]
    name = "Twitter"
    icon = "fa fa-twitter fa-2x"
    weight = 3
    url = "https://twitter.com/kconragan/"


# future self, this is the command for exporting json data
# exiftool -w %f.%e.json -json -struct -G -XMP:All -EXIF:All -IPTC:All . | sed -e "s/^EXIF:|^XMP://g"

# Set to enable Plausible Analytics.
plausible_domain = ""

[params.gallerydeluxe]

    # Shuffle the images in the gallery to give the impression of a new gallery each page load.
    shuffle = false

    # Reverse the order of the images in the gallery.
    reverse = true

    # Enable Exif data in the gallery.
    # See https://gohugo.io/content-management/image-processing/#exif-data for how to filter tags.
    enable_exif = true

    # Optional watermark file for the large images.
    [params.gallerydeluxe.watermark]
        image = "images/gopher-hero8.png" # relative to /assets
        posx  = "left"                    # one of "left", "center", "right"
        posy  = "bottom"                  # one of "top", "center", "bottom"

[build]
    [[build.cacheBusters]]
        source = 'content/.*\.(png|jpg|jpeg)'
        target = '(json)'
    [[build.cacheBusters]]
        source = 'layouts/.*'
        target = '(json)'

[caches]
    [caches.images]
        dir    = ':cacheDir/gallerydeluxe'
        maxAge = "4320h"                   # 6 months.

[imaging]
    resampleFilter = "CatmullRom"
    quality        = 71
    anchor         = "smart"
    [imaging.exif]
        disableDate    = false
        disableLatLong = true
        includeFields  = 'Artist|LensModel|FNumber|ExposureTime'

[server]
    [[server.headers]]
        for = '/**'
        [server.headers.values]
            Referrer-Policy = 'strict-origin-when-cross-origin'

[module]
    [[module.mounts]]
        source = "assets"
        target = "assets"
    [[module.mounts]]
        source = "layouts"
        target = "layouts"
    [[module.mounts]]
        source = "content"
        target = "content"
    [[module.mounts]]
        source = "static"
        target = "static"
    [[module.imports]]
        path = "github.com/bep/gallerydeluxe"
