baseURL = 'https://conragan.com'
languageCode = 'en-us'
  title = 'Kai Conragan'
theme = "hugo-coder"
defaultContentLanguage = "en"
publishDir = "public"

enableGitInfo = true

# BaseURL Overrides 
[env]
  [env.development]
    baseURL = "http://localhost:1313/"
  [env.production]
    baseURL = "https://conragan.com/"

[permalinks]
  blog = "/blog/:year/:filename/"

# Menu links - OK as is
[[menu.main]]
  name = "Photography"
  weight = 1
  url = "photography/"
[[menu.main]]
  name = "Blog"
  weight = 2
  url = "blog/"
[[menu.main]]
  name = "About"
  weight = 3
  url = "about/"

[params]
  author = "Kai Conragan"
  info = "Tech leader, UX Designer, [Writer](/blog/), and [Photographer](/photography/)."
  description = "Kai Conragan's personal website"
  keywords = "landscape photography, sports photography, wildlife photogrpahy, bird photography, design, travel, ux, user experience"
  avatarurl = "img/headshot.webp"
  faviconSVG = "img/favicon.svg"
  favicon_32 = "img/favicon-32x32.png"
  favicon_16 = "img/favicon-16x16.png"
  colorScheme = "auto"
  hidecolorschemetoggle = false
  customCSS = ["css/conragan.css"]
  customJS = ["js/conragan.js"]

[params.googleTagManager]
  id = "G-4R2W76V53L"

[params.meta]
  name = "p:domain_verify"
  content = "5e42b91db4d05707d32a9894e67423c5"

# Social links - OK as is
[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/kconragan/"
[[params.social]]
  name = "LinkedIn"
  icon = "fa fa-linkedin fa-2x"
  weight = 2
  url = "https://www.linkedin.com/in/kconragan/"
[[params.social]]
  name = "Twitter"
  icon = "fa fa-twitter fa-2x"
  weight = 3
  url = "https://twitter.com/kconragan/"

plausible_domain = "" #OK as is

[params.gallerydeluxe]
  shuffle = false
  reverse = true
  enable_exif = true
[params.gallerydeluxe.watermark]
  image = "images/gopher-hero8.png"
  posx = "left"
  posy = "bottom"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[markup.highlight] # Keep highlight separate

[build]
  [[build.cachebusters]]
    source = 'content/.*\.(png|jpg|jpeg)'
    target = '(json)'
  [[build.cachebusters]]
    source = 'layouts/.*'
    target = '(json)'

[caches]
  [caches.images]
    dir = ':cacheDir/gallerydeluxe'
    maxAge = "4320h"

[imaging]
  resampleFilter = "CatmullRom"
  quality = 71
  anchor = "Smart"
[imaging.exif]
  disableDate = false
  disableLatLong = true
  includeFields = 'Artist|LensModel|FNumber|ExposureTime'

[server]
  [[server.headers]]
    for = '/**'
  [server.headers.values]
    Referrer-Policy = 'strict-origin-when-cross-origin'

[module]
  [[module.mounts]]
    source = "assets"
    target = "assets"
  [[module.mounts]]
    source = "layouts"
    target = "layouts"
  [[module.mounts]]
    source = "content"
    target = "content"
  [[module.mounts]]
    source = "static"
    target = "static"
